name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
        working-directory: docs

      - run: npm run build
        working-directory: docs

      - uses: actions/upload-artifact@v2
        with:
          name: document
          path: docs/build

      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs/build
        if: github.event_name == 'push'
